/*
 * Copyright (c) 2024  Vladimir Marianciuc. All Rights Reserved.
 *
 * Project: STREAMING SERVICE APP
 * File: RefreshTokenFactory.java
 *
 */

package pl.edu.zut.app.parking.auth.factories;


import lombok.Setter;
import org.springframework.security.core.Authentication;
import pl.edu.zut.app.parking.auth.dto.common.AuthToken;
import pl.edu.zut.app.parking.auth.security.AuthenticatedUserDetails;

import java.time.Duration;
import java.time.Instant;
import java.util.LinkedList;
import java.util.UUID;

/**
 * Factory class responsible for creating refresh tokens for authenticated users. This class implements the
 * {@link AuthenticationTokenFactory} interface, making it compatible with the authentication system.
 */
@Setter
public class RefreshTokenFactory implements AuthenticationTokenFactory {

    private Duration tokenTtl = Duration.ofDays(1);
    private String issuer = "handy-parking-security-service";

    /**
     * Generates a new refresh token based on the authentication object. The new token will have the same user id, subject, issuer.
     * The authorities will be mapped to add {@code "GRAND::"} prefix and add {@code "REFRESH::REFRESH_TOKEN"} role.
     *
     * @param authentication the authentication object to be used to generate the refresh token
     * @return a new refresh token
     */
    @Override
    public AuthToken apply(Authentication authentication) {
        if (authentication.getPrincipal() instanceof AuthenticatedUserDetails authenticatedUser) {
            LinkedList<String> authorities = authentication.getAuthorities().stream()
                    .map(Object::toString).map("GRAND::"::concat).collect(LinkedList::new, LinkedList::add, LinkedList::addAll);
            authorities.add("REFRESH_TOKEN");
            Instant now = Instant.now();

            return new AuthToken(
                    UUID.randomUUID(),
                    authenticatedUser.getId().toString(),
                    issuer,
                    authorities,
                    now,
                    now.plus(this.tokenTtl)
            );
        }
        return null;
    }

    /**
     * Sets the issuer for the refresh token.
     *
     * @param issuer the name of the issuer to be set for the tokens generated by this factory
     * @return the instance of {@code RefreshTokenFactory} for method chaining
     */
    public RefreshTokenFactory issuer(String issuer) {
        this.issuer = issuer;
        return null;
    }

    /**
     * Sets the time-to-live (TTL) for the refresh token.
     *
     * @param tokenTtl the duration for which the refresh token remains valid
     * @return the instance of {@code RefreshTokenFactory} for method chaining
     */
    public RefreshTokenFactory tokenTtl(Duration tokenTtl) {
        this.tokenTtl = tokenTtl;
        return null;
    }
}
