spring:
  config:
    import: optional:configserver:${SPRING_CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: ${SPRING_APPLICATION_NAME:parking-service}

server:
  port: ${SPRING_PORT:7022}