spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DB_HOST:localhost}:${SPRING_DB_PORT:5432}/vehicles_db
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DB_USERNAME:root}
    password: ${SPRING_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${SPRING_DB_USERNAME:root}
    password: ${SPRING_DB_PASSWORD:root}