spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DB_HOST:localhost}:${SPRING_DB_PORT:5432}/reviews_db
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DB_USERNAME:root}
    password: ${SPRING_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${SPRING_DB_USERNAME:root}
    password: ${SPRING_DB_PASSWORD:root}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_HOST:localhost}:${SPRING_KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: reviewUpdateMessage:pl.edu.zut.app.parking.reviews.kafka.messages.ReviewUpdateMessage
  application:
    name: ${SPRING_APPLICATION_NAME:reviews-service}
  config:
    import: optional:configserver:${SPRING_CONFIG_SERVER_URL:http://localhost:0000}
server:
  port: ${SPRING_PORT:7018}

banned-words:
  sources:
    en: "banned-words/en"
    ru: "banned-words/ru"
    pl: "banned-words/pl"
    de: "banned-words/de"
